# Imagen base ligera de Python
FROM python:3.12-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar todo el contenido del proyecto al contenedor
COPY . .

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 8000

# Instalar dependencias del proyecto
RUN pip install --no-cache-dir "poetry"

# Instalar dependencias del proyecto usando Poetry
RUN poetry install --no-root --only main --no-cache

# Definir comando para correr la aplicación
CMD [ "poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
