[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "ᓚᘏᗢ !?",email = "datamayo.211@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "pymongo (>=4.17.0,<5.0.0)",
    "fastapi[standard] (>=0.141.1,<0.142.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
